### ISSUE TITLE
The module "realestate" is not available

### ISSUE THREAD

**Issue by CosmoGao** [PKUJohnson/OpenData#1]
After update to version 0.4.7 (Python 3.6.5), the module "realestate" cannot get the data from Anjuke, both get_city_list() and get_real_house_price() returned None.
_I have review the module, I found that Anjuke add 2 CAPTCHA, so Anjuke_Agent will not able to get the data._

P.S.There are sth wrong on the wiki of realestate:
```Python
df = realestate.realestate.get_real_house_price('北京')
```
THX

**Comment by PKUJohnson** [comment]
I have test the interface， it works！
BTW， i have fixed the wiki. 
Thanks.

**Comment by CosmoGao** [comment]
Maybe some IP address will touch off the CAPTCHA like this, which will cause the problem.
![image](https://user-images.githubusercontent.com/9216968/42304994-85505514-805b-11e8-9ca6-7584af2b5c09.png)
Besides, the interface doesn't work with the JSONDecodeError:
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by PKUJohnson** [comment]
thanks。
