### ISSUE TITLE
aqi 接口失效

### ISSUE THREAD

**Issue by xgdgsc** [PKUJohnson/OpenData#18]
aqi 接口失效了, http://datacenter.mee.gov.cn 新域名拒绝访问

**Comment by PKUJohnson** [comment]
的确是这样的，新网站反爬机制很强，欢迎大家贡献解决方案

**Comment by yuqianma** [comment]
作者竟然整理了这么多，真是有心。
但是我觉得这个很难维护下去，毕竟稍微加一点反爬，就要花很多精力去找方法。
作者有用过puppeteer吗？
https://github.com/GoogleChrome/puppeteer
直接用浏览器，虽然缺点也很明显。

**Comment by PKUJohnson** [comment]
这个项目就是希望为非技术人士获取数据提供便利，专业技术人员的选择会更多一些。谢谢支持！

**Comment by PKUJohnson** [comment]
Hi all, 由于环保部数据中心网站限流，无法从官方爬取数据，因此重新开发了aqi2这个接口，数据来源aqistudy，欢迎使用，本issue可以关闭。
