### ISSUE TITLE
获取私募基金get_fund_nav失败

### ISSUE THREAD

**Issue by jianfly** [PKUJohnson/OpenData#6]
请问在获取私募基金数据时，get_fund_list是成功的，但get_fund_nav获取数据失败

**Comment by PKUJohnson** [comment]
由于排排网修改了页面的算法，非常变态的加密规则。我已经提交新的代码到master分支。

会合并到下个版本。

**Comment by qmhedging** [comment]
似乎现在页面加密算法升级了，能否继续更新？
